### ISSUE TITLE
During fishing, the fishing line breaks

### ISSUE THREAD

**Issue by PsihologA** [ingego/new_world#1]
I turned on the bot, everything worked fine. He threw a fishing line into the water, during the checkpoint, as it should be, he clicked 1 time and began to pull the line. But at the same time he pulled fishing line to such an extent that it blushed and tore. I don't know how to solve this problem
![image](https://user-images.githubusercontent.com/94066122/141148711-2fbc538f-e5aa-450d-906f-fedd4bfe6cf9.png)

**Comment by TangoRain** [comment]
Бот ни разу не выловил рыбу? насколько минут запустил бота ?

**Comment by PsihologA** [comment]
Ни разу не выловил, все время леска рвется, минут на 20

**Comment by PsihologA** [comment]
он как бы начинает тянуть, но не останавливается
